### ISSUE TITLE
runtimeerro: maximum recursion depth

### ISSUE THREAD

**Issue by pedrotnascimento** [codingforentrepreneurs/Advancing-the-Blog#2]
Hello,
I tried to do as the Blog API with Django Rest Framework 2 of 33 - Getting Started & Installations says
and when I try to do python manage.py makemigrations it gives the error below:(actually any use of manage.py gives that)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 324, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django\contrib\auth\models.py", line 297, in <module>
    class AbstractUser(AbstractBaseUser, PermissionsMixin):
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 251, in __new__
    new_class.add_to_class(field.name, new_field)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 299, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 672, in contribute_to_class
    cls._meta.add_field(self)
  File "C:\Python27\lib\site-packages\django\db\models\options.py", line 312, in add_field
    self.local_fields.insert(bisect(self.local_fields, field), field)
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
.......(a lot of repetion of the two lines above)
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
RuntimeError: maximum recursion depth exceeded while calling a Python object

Do you know what this can mean? Am I doing something wrong?
pip freeze is just like the video, my python version is 2.7

**Comment by pedrotnascimento** [comment]
So, I made manage.py works, happens that it 's not working for django 1.9.5 as the tutorial suggest(at least for me)﻿
